"use client";

import { useCallback, useSyncExternalStore } from "react";

export type Language = "en" | "km";

const languageEvent = "aurelia-language-change";

export const translations: Record<string, string> = {
  Home: "ទំព័រដើម",
  Cars: "រថយន្ត",
  Brands: "ម៉ាករថយន្ត",
  About: "អំពីយើង",
  Contact: "ទំនាក់ទំនង",
  Favorites: "ចំណូលចិត្ត",
  "Sign in": "ចូលគណនី",
  Explore: "ស្វែងរក",
  Company: "ក្រុមហ៊ុន",
  Visit: "ទីតាំង",
  Compare: "ប្រៀបធៀប",
  "Sell your car": "លក់រថយន្តរបស់អ្នក",
  Careers: "ការងារ",
  Journal: "ទិនានុប្បវត្តិ",
  "Exceptional cars, transparently sourced. We make discovering your next drive feel as rewarding as owning it.": "រថយន្តដ៏ពិសេស ដែលមានប្រភពច្បាស់លាស់។ យើងធ្វើឱ្យការស្វែងរករថយន្តបន្ទាប់របស់អ្នកមានភាពរីករាយ។",
  "Curated inventory": "រថយន្តដែលបានជ្រើសរើស",
  "Cars worth driving.": "រថយន្តដែលស័ក្តិសមនឹងការបើកបរ។",
  "Search make or model": "ស្វែងរកម៉ាក ឬម៉ូដែល",
  "Newest first": "ថ្មីបំផុតមុន",
  "Price: low to high": "តម្លៃ៖ ទាបទៅខ្ពស់",
  "Price: high to low": "តម្លៃ៖ ខ្ពស់ទៅទាប",
  Filters: "តម្រង",
  "Reset all": "កំណត់ឡើងវិញ",
  Brand: "ម៉ាក",
  "Fuel type": "ប្រភេទឥន្ធនៈ",
  Condition: "ស្ថានភាព",
  Color: "ពណ៌",
  Year: "ឆ្នាំ",
  "Maximum mileage": "ចម្ងាយអតិបរមា",
  vehicles: "រថយន្ត",
  available: "មាន",
  "No exact matches": "រកមិនឃើញរថយន្តដែលត្រូវគ្នា",
  "Try adjusting your filters.": "សូមសាកល្បងកែតម្រងរបស់អ្នក។",
  Show: "បង្ហាញ",
  All: "ទាំងអស់",
  Call: "ហៅទូរសព្ទ",
  "Contact dealer": "ទាក់ទងអ្នកលក់",
  "Copied!": "បានចម្លង!",
  "Aurelia concierge": "សេវាកម្ម Aurelia",
  "Ask about this car": "សាកសួរអំពីរថយន្តនេះ",
  "Full name": "ឈ្មោះពេញ",
  "Email address": "អាសយដ្ឋានអ៊ីមែល",
  "Phone number": "លេខទូរសព្ទ",
  "How can we help?": "តើយើងអាចជួយអ្វីបាន?",
  "Send request": "ផ្ញើសំណើ",
  "Browse cars": "មើលរថយន្ត",
  "Freshly selected": "ទើបជ្រើសរើសថ្មីៗ",
  "Featured cars": "រថយន្តពិសេស",
  "Standout vehicles chosen by our specialists.": "រថយន្តឆ្នើមដែលជ្រើសរើសដោយអ្នកជំនាញរបស់យើង។",
  "View all inventory": "មើលរថយន្តទាំងអស់",
  "Explore by marque": "ស្វែងរកតាមម៉ាក",
  "The Aurelia standard": "ស្តង់ដារ Aurelia",
  "Confidence at every turn.": "ទំនុកចិត្តគ្រប់ពេលបើកបរ។",
  "Buying a remarkable car should feel remarkable. Our process is transparent, personal, and built around complete peace of mind.": "ការទិញរថយន្តដ៏អស្ចារ្យគួរតែផ្តល់បទពិសោធន៍ដ៏អស្ចារ្យ។ ដំណើរការរបស់យើងមានតម្លាភាព ផ្ទាល់ខ្លួន និងផ្តល់ភាពស្ងប់ចិត្តពេញលេញ។",
  "150-point inspection": "ការត្រួតពិនិត្យ ១៥០ ចំណុច",
  "Every vehicle is independently assessed and reconditioned.": "រថយន្តគ្រប់គ្រឿងត្រូវបានត្រួតពិនិត្យ និងរៀបចំឡើងវិញដោយឯករាជ្យ។",
  "7-day exchange": "ប្តូរបានក្នុងរយៈពេល ៧ ថ្ងៃ",
  "Change your mind? Exchange your vehicle without the stress.": "ប្តូរចិត្តមែនទេ? អ្នកអាចប្តូររថយន្តដោយគ្មានកង្វល់។",
  "A dedicated specialist": "អ្នកជំនាញផ្ទាល់ខ្លួន",
  "One expert stays with you from first question to handover.": "អ្នកជំនាញម្នាក់នឹងជួយអ្នកចាប់ពីសំណួរដំបូងរហូតដល់ការប្រគល់រថយន្ត។",
  "Browse the collection": "មើលរថយន្តទាំងអស់",
  "Iconic marques": "ម៉ាករថយន្តល្បីៗ",
  "Choose your badge.": "ជ្រើសរើសម៉ាកដែលអ្នកពេញចិត្ត។",
  "Explore our collection by manufacturer, from celebrated performance houses to modern electric pioneers.": "ស្វែងរករថយន្តតាមក្រុមហ៊ុនផលិត ចាប់ពីម៉ាករថយន្តសមត្ថភាពខ្ពស់រហូតដល់រថយន្តអគ្គិសនីទំនើប។",
  "Our story": "រឿងរ៉ាវរបស់យើង",
  "Cars with character. Service with soul.": "រថយន្តមានអត្តសញ្ញាណ។ សេវាកម្មដោយយកចិត្តទុកដាក់។",
  "Founded by lifelong enthusiasts, Aurelia exists to make the world’s most engaging cars easier to discover and more rewarding to own. Every vehicle is selected for its condition, provenance, and the feeling it creates from behind the wheel.": "Aurelia ត្រូវបានបង្កើតឡើងដោយអ្នកស្រឡាញ់រថយន្ត ដើម្បីធ្វើឱ្យរថយន្តល្អបំផុតងាយស្រួលស្វែងរក និងរីករាយក្នុងការកាន់កាប់។ រថយន្តគ្រប់គ្រឿងត្រូវបានជ្រើសរើសតាមស្ថានភាព ប្រភព និងបទពិសោធន៍បើកបរ។",
  Curated: "ជ្រើសរើសដោយយកចិត្តទុកដាក់",
  Transparent: "តម្លាភាព",
  Personal: "ផ្ទាល់ខ្លួន",
  "We choose fewer, better cars—never inventory for inventory’s sake.": "យើងជ្រើសរើសរថយន្តតិចតែមានគុណភាពខ្ពស់។",
  "Clear histories, honest condition reports, and no hidden surprises.": "ប្រវត្តិច្បាស់លាស់ របាយការណ៍ស្ថានភាពត្រឹមត្រូវ និងគ្មានការលាក់បាំង។",
  "A real specialist, accessible whenever you need a considered answer.": "អ្នកជំនាញពិតប្រាកដត្រៀមជួយនៅពេលអ្នកត្រូវការ។",
  "Vehicle overview": "ព័ត៌មានទូទៅអំពីរថយន្ត",
  Mileage: "ចម្ងាយបានបើក",
  Engine: "ម៉ាស៊ីន",
  Horsepower: "កម្លាំងសេះ",
  Transmission: "ប្រអប់លេខ",
  Fuel: "ឥន្ធនៈ",
  "Drive type": "ប្រភេទបើកបរ",
  Exterior: "ពណ៌ខាងក្រៅ",
  Interior: "ផ្នែកខាងក្នុង",
  Seats: "ចំនួនកៅអី",
  "Features & technology": "លក្ខណៈពិសេស និងបច្ចេកវិទ្យា",
  "Blind spot monitoring": "ប្រព័ន្ធតាមដានចំណុចងងឹត",
  "Lane keeping assistance": "ប្រព័ន្ធជំនួយរក្សាគន្លង",
  "Emergency braking": "ប្រព័ន្ធហ្វ្រាំងបន្ទាន់",
  "Parking sensors": "ឧបករណ៍ចាប់សញ្ញាចតរថយន្ត",
  "Interactive map placeholder": "ទីតាំងផែនទី",
  "Inspected. Protected. Ready.": "បានត្រួតពិនិត្យ។ មានការការពារ។ រួចរាល់។",
  "You may also like": "អ្នកក៏អាចចូលចិត្ត",
  "Side by side": "ប្រៀបធៀបជាប់គ្នា",
  "Compare cars": "ប្រៀបធៀបរថយន្ត",
  "Compare up to three vehicles to find your best fit.": "ប្រៀបធៀបរថយន្តរហូតដល់បីគ្រឿង ដើម្បីរកជម្រើសល្អបំផុត។",
  Remove: "ដកចេញ",
  "Your comparison is empty": "មិនទាន់មានរថយន្តសម្រាប់ប្រៀបធៀប",
  "Add up to three cars from the inventory.": "បន្ថែមរថយន្តរហូតដល់បីគ្រឿងពីបញ្ជីរថយន្ត។",
  "Browse inventory": "មើលបញ្ជីរថយន្ត",
  "Your shortlist": "បញ្ជីរបស់អ្នក",
  "Saved cars": "រថយន្តដែលបានរក្សាទុក",
  "Keep the cars you love close at hand.": "រក្សាទុករថយន្តដែលអ្នកពេញចិត្ត។",
  "Nothing saved yet": "មិនទាន់មានអ្វីបានរក្សាទុក",
  "Tap the heart on any vehicle to add it here.": "ចុចរូបបេះដូងលើរថយន្តណាមួយដើម្បីបន្ថែមនៅទីនេះ។",
  "Explore cars": "មើលរថយន្ត",
  "Talk to a specialist": "និយាយជាមួយអ្នកជំនាញ",
  "We’re here to help.": "យើងនៅទីនេះដើម្បីជួយអ្នក។",
  "Whether you’re searching, selling, or simply curious, our team is ready with a thoughtful answer.": "មិនថាអ្នកកំពុងស្វែងរក លក់ ឬចង់សាកសួរទេ ក្រុមការងាររបស់យើងត្រៀមជួយអ្នក។",
  "Visit us": "មកកាន់ទីតាំងយើង",
  Email: "អ៊ីមែល",
  Hours: "ម៉ោងធ្វើការ",
  "Map placeholder": "ទីតាំងផែនទី",
  Name: "ឈ្មោះ",
  Phone: "ទូរសព្ទ",
  Subject: "ប្រធានបទ",
  Message: "សារ",
  "Select a topic": "ជ្រើសរើសប្រធានបទ",
  "Vehicle enquiry": "សាកសួរអំពីរថយន្ត",
  "Sell my car": "លក់រថយន្តរបស់ខ្ញុំ",
  Financing: "ហិរញ្ញប្បទាន",
  "General question": "សំណួរទូទៅ",
  "Send message": "ផ្ញើសារ",
  "Message received.": "បានទទួលសាររបស់អ្នក។",
  "A specialist will respond within one business day.": "អ្នកជំនាញនឹងឆ្លើយតបក្នុងរយៈពេលមួយថ្ងៃធ្វើការ។",
  "Aurelia account": "គណនី Aurelia",
  "Welcome back.": "សូមស្វាគមន៍មកវិញ។",
  "Join Aurelia.": "ចូលរួមជាមួយ Aurelia។",
  "Reset your password.": "កំណត់ពាក្យសម្ងាត់ឡើងវិញ។",
  "Save cars, compare choices, and manage your enquiries.": "រក្សាទុករថយន្ត ប្រៀបធៀបជម្រើស និងគ្រប់គ្រងសំណួររបស់អ្នក។",
  Password: "ពាក្យសម្ងាត់",
  "Forgot password?": "ភ្លេចពាក្យសម្ងាត់?",
  "Create account": "បង្កើតគណនី",
  "Send reset link": "ផ្ញើតំណកំណត់ឡើងវិញ",
  "Sell with confidence": "លក់ដោយទំនុកចិត្ត",
  "Your car. Our audience.": "រថយន្តរបស់អ្នក។ អតិថិជនរបស់យើង។",
  "Create a polished listing in a few simple steps. No obligation, no hidden fees.": "បង្កើតបញ្ជីលក់ដ៏ល្អក្នុងជំហានងាយៗ ដោយគ្មានកាតព្វកិច្ច និងថ្លៃលាក់កំបាំង។",
  Vehicle: "រថយន្ត",
  Specifications: "លក្ខណៈបច្ចេកទេស",
  Price: "តម្លៃ",
  Photos: "រូបថត",
  Preview: "មើលជាមុន",
  Step: "ជំហាន",
  of: "នៃ",
  "Tell us about your car": "ប្រាប់យើងអំពីរថយន្តរបស់អ្នក",
  "Add the key specifications": "បន្ថែមលក្ខណៈបច្ចេកទេសសំខាន់ៗ",
  "Set your asking price": "កំណត់តម្លៃលក់",
  "Show it at its best": "បង្ហាញរថយន្តឱ្យបានល្អបំផុត",
  "How can we reach you?": "តើយើងអាចទាក់ទងអ្នកដោយរបៀបណា?",
  "Review your listing": "ពិនិត្យបញ្ជីលក់របស់អ្នក",
  Make: "ម៉ាក",
  Model: "ម៉ូដែល",
  VIN: "លេខតួរថយន្ត",
  "Body type": "ប្រភេទតួរថយន្ត",
  Features: "លក្ខណៈពិសេស",
  "Exterior color": "ពណ៌ខាងក្រៅ",
  "Asking price": "តម្លៃលក់",
  Back: "ថយក្រោយ",
  Continue: "បន្ត",
  "Submit listing": "ដាក់ស្នើបញ្ជីលក់",
  Dashboard: "ផ្ទាំងគ្រប់គ្រង",
  "My Cars": "រថយន្តរបស់ខ្ញុំ",
  Messages: "សារ",
  Profile: "ប្រវត្តិរូប",
  Settings: "ការកំណត់",
  "My account": "គណនីរបស់ខ្ញុំ",
  "List a car": "ដាក់លក់រថយន្ត",
  "My listings": "បញ្ជីលក់របស់ខ្ញុំ",
  "Test drives": "ការសាកបើកបរ",
  "Recently viewed": "បានមើលថ្មីៗ",
  "View all": "មើលទាំងអស់",
  "Upcoming test drive": "ការសាកបើកបរនាពេលខាងមុខ",
  "View appointment": "មើលការណាត់ជួប",
  Added: "បានបន្ថែម",
  "Add favorite": "បន្ថែមចំណូលចិត្ត",
  "Remove favorite": "ដកចេញពីចំណូលចិត្ត",
  Gasoline: "សាំង",
  Electric: "អគ្គិសនី",
  Hybrid: "ហាយប្រ៊ីដ",
  New: "ថ្មី",
  Certified: "បានបញ្ជាក់គុណភាព",
  Automatic: "ស្វ័យប្រវត្តិ",
  Manual: "លេខដៃ",
  "Curated performance. Uncompromised service.": "សមត្ថភាពដែលបានជ្រើសរើស។ សេវាកម្មឥតខ្ចោះ។",
  "Find your": "ស្វែងរក",
  "perfect drive.": "រថយន្តដ៏ស័ក្តិសមរបស់អ្នក។",
  "Discover a considered collection of exceptional cars, each inspected and ready for the road ahead.": "ស្វែងរករថយន្តដ៏ពិសេសដែលបានជ្រើសរើស និងត្រួតពិនិត្យរួចរាល់សម្រាប់ការធ្វើដំណើរ។",
  "Cars delivered": "រថយន្តបានប្រគល់",
  "Years of expertise": "ឆ្នាំនៃបទពិសោធន៍",
  "Client rating": "ការវាយតម្លៃពីអតិថិជន",
  "Trusted partners": "ដៃគូដែលទុកចិត្ត",
  "Recently arrived": "ទើបមកដល់ថ្មីៗ",
  "New to the collection": "រថយន្តថ្មីក្នុងការប្រមូលផ្តុំ",
  "Owners’ stories": "រឿងរ៉ាវពីម្ចាស់រថយន្ត",
  "Driven by trust": "ជំរុញដោយទំនុកចិត្ត",
  "The most refreshingly transparent car purchase I’ve ever made.": "នេះជាបទពិសោធន៍ទិញរថយន្តដែលមានតម្លាភាពបំផុតដែលខ្ញុំធ្លាប់មាន។",
  "Every detail was considered—from the first call to delivery day.": "គ្រប់ព័ត៌មានលម្អិតត្រូវបានយកចិត្តទុកដាក់ ចាប់ពីការហៅដំបូងរហូតដល់ថ្ងៃប្រគល់។",
  "A truly premium experience without the pressure you expect elsewhere.": "បទពិសោធន៍លំដាប់ខ្ពស់ពិតប្រាកដ ដោយគ្មានសម្ពាធ។",
  "Stay ahead of the curve.": "ទទួលបានព័ត៌មានមុនគេ។",
  "New arrivals, buying guides, and private sale invitations—delivered thoughtfully.": "ទទួលព័ត៌មានរថយន្តថ្មី ការណែនាំទិញ និងការអញ្ជើញលក់ពិសេស។",
  "Your email address": "អាសយដ្ឋានអ៊ីមែលរបស់អ្នក",
  "Join the list": "ចូលរួមបញ្ជី",
  "Max price": "តម្លៃអតិបរមា",
  "All makes": "ម៉ាកទាំងអស់",
  "Any model": "ម៉ូដែលណាមួយ",
  "No limit": "មិនកំណត់",
  Search: "ស្វែងរក",
  "Premium sound system": "ប្រព័ន្ធសំឡេងកម្រិតខ្ពស់",
  "Adaptive cruise control": "ប្រព័ន្ធគ្រប់គ្រងល្បឿនស្វ័យប្រវត្តិ",
  "360° camera": "កាមេរ៉ា ៣៦០ ដឺក្រេ",
  "Heated seats": "កៅអីកម្តៅ",
  "Wireless Apple CarPlay": "Apple CarPlay ឥតខ្សែ",
   "Please enter your name": "សូមបញ្ចូលឈ្មោះរបស់អ្នក",
  "Enter a valid email": "សូមបញ្ចូលអ៊ីមែលត្រឹមត្រូវ",
  "Enter a valid phone number": "សូមបញ្ចូលលេខទូរសព្ទត្រឹមត្រូវ",
  "Choose a subject": "សូមជ្រើសរើសប្រធានបទ",
  "Please add a little more detail": "សូមបន្ថែមព័ត៌មានលម្អិតបន្តិច",
  "Vehicle Comparison": "ការប្រៀបធៀបរថយន្ត",
  "Compare specifications, powertrain metrics, dimensions, and standard amenities across up to four vehicles.": "ប្រៀបធៀបលក្ខណៈបច្ចេកទេស កម្លាំងម៉ាស៊ីន ទំហំ និងបរិក្ខារស្តង់ដារនៃរថយន្តរហូតដល់ ៤ គ្រឿង។",
  "Search make, model, year, body style...": "ស្វែងរកម៉ាក ម៉ូដែល ឆ្នាំ ប្រភេទតួរថយន្ត...",
  "Curated Selection": "ការជ្រើសរើសដោយយកចិត្តទុកដាក់",
  "150-Point Certification": "ការត្រួតពិនិត្យ ១៥០ ចំណុច",
  "Transparent Provenance": "តម្លាភាព និងប្រវត្តិជាក់ស្តែង",
  "Private Client Concierge": "អ្នកជំនាញផ្ទាល់ខ្លួន",
};

function getLanguage(): Language {
  if (typeof window === "undefined") return "en";
  return localStorage.getItem("language") === "km" ? "km" : "en";
}

export function useLanguage() {
  const subscribe = useCallback((onChange: () => void) => {
    window.addEventListener("storage", onChange);
    window.addEventListener(languageEvent, onChange);
    return () => {
      window.removeEventListener("storage", onChange);
      window.removeEventListener(languageEvent, onChange);
    };
  }, []);

  const language = useSyncExternalStore(subscribe, getLanguage, () => "en" as Language);

  const toggleLanguage = useCallback(() => {
    const next: Language = getLanguage() === "en" ? "km" : "en";
    localStorage.setItem("language", next);
    document.documentElement.lang = next;
    window.dispatchEvent(new Event(languageEvent));
  }, []);

  const t = useCallback((text: string) => language === "km" ? translations[text] ?? text : text, [language]);

  return { language, t, toggleLanguage };
}
